### ISSUE TITLE
Transaction on the Mac OSX Wallet is shown twice

### ISSUE THREAD

**Issue by sanjay-shah** [anthony19114/MyBitcoinZ#1]
The transaction on the Mac OSX Wallet is shown twice. txid: 5148785be9a5e04c46b16e2fe7037fc75e60418a0e1f7350edf97c3431393309

![image](https://user-images.githubusercontent.com/1676317/31332304-bf453ffe-ac9a-11e7-996d-b699c4fd0e74.png)

**Comment by anthony19114** [comment]
Is this happening also for Windows and Linux versions? I also see the duplicate transaction 'Notification' for iOS version also.

**Comment by sanjay-shah** [comment]
I haven't tested the Windows, as I don't have one. But I will test out the Linux/Ubuntu 16.04 version and let you know.

**Comment by CDminer** [comment]
I can confirm that the same duplication is taking place in the Windows wallet, visible on both the home page and under Recent Transactions:

![image](https://user-images.githubusercontent.com/32721755/31472247-9204e3f0-aebb-11e7-88a9-6a6589b9f676.png)


However, when you go into the wallet proper, you see that only one transaction took place:

![image](https://user-images.githubusercontent.com/32721755/31472176-3a151fd4-aebb-11e7-88fe-b56d53b3c5dc.png)

More bemusing is the conversion from BTCZ to USD.  Apparently still showing the value of Bitcoin instead of BitCoinZ. Wishful thinking, perhaps!

**Comment by anthony19114** [comment]
It is known that it shows duplicate transactions under "Recent transactions" across all platforms, due to notifications turned on. It is currently showing the btcusd pair value for the coin since there is no exchange using an active BTCZ_USD pair. Once its on an exchange it'll be corrected to the correct value.

**Comment by anthony19114** [comment]
MyBitcoinZ is no longer supported by this repository, and has no technical support.
