### ISSUE TITLE
Can't Send Transaction

### ISSUE THREAD

**Issue by neurans** [anthony19114/MyBitcoinZ#3]
HI Anthony, 

Love your wallet, 
Can you help me figure out why this error? 

![image](https://user-images.githubusercontent.com/32342476/32150539-c959f0c4-bcea-11e7-9fc2-6c9e87a6c3c7.png)

**Comment by neurans** [comment]
I sent a 1 BTCZ transaction and it worked fine, send a 2,590 BTCz transaction, gave me error, coins are now locked and didn't arrive to destination. What can I do?

**Comment by anthony19114** [comment]
You received coins directly from a mined block without shielding. All mined
coins must pass through a z_address before they can be spent.

This is quite a problem that some pools are adding donation addresses and
other addresses into the list of addresses to submit when block found.

**Comment by neurans** [comment]
How can I solve this?

**Comment by neurans** [comment]
If I click on delete payment proposal. Will I recover them?

**Comment by neurans** [comment]
OK, I did recover them (removed the lock) how can I make this coins usable?

**Comment by anthony19114** [comment]
The 1 BTCZ was not from a mined block input. The others are. What needs to be done is input the private key for the address that has the 'locked funds' from not being shielded. Import them to a zcashd coin base, either the linux or windows wallet etc. Then start sending the inputs to a z_address then back to a t_address.

https://coinomi.com/recovery-phrase-tool.html

You can enter your recovery phrase there. Then the bip32 derivation path is m/44'/0'/0'/0

Then your addresses with private keys will start to list.

Input to the coinbase using command line or windows SWING UI wallet.

zcash-cli.exe help
./zcash-cli help

Now you need to get a z_address.. so
zcash-cli z_getnewaddress
then now you need to start sending the inputs that you see on that t1 address from the explorer. I recommend shielding the same exact amounts that were sent to you since I believe you have mined coin inputs and other normal inputs in the same address.

zcash-cli z_sendmany "t1J8GmG3BCLp9iPHzUQ6d1u2cYJ2geRBSQg" "[{\"amount\": 249.999, \"address\": \"zcChRTHZqfiHfeu73uHio8cS1iM2kWwgoJtMkJWsa29319DXroZkR3HvfkfNwpBP1uRee3MmfUJ7HC9XnpyDgUJ5q6fSRCB\"}]"
you need to change the t1 address and z address to owns in your own.
Then it gives you an opid then with the opid you can lookup the process of the transaction. Or all this can be done in the windows swing ui wallet also. 

Its bad procedure to send coins by aggregating t1 addresses before the funds are shielded.

**Comment by neurans** [comment]
How can I export private keys from this wallet? I will try to unshield them from the other local wallet. IT has a Z address on it.

**Comment by neurans** [comment]
Man, I was able to do all this, but cant get to download keys. Don't know how to, Can I PM you the secret phrase so that you recover these and send me so that I can import to the local wallet? You can keep some of the BTCz as a tip for helping me.

**Comment by neurans** [comment]
I was able to see hundreds of Private Keys and imported 2 of them to try them. No balance. Is there an easier way?  Download the whole private key with all these?

**Comment by anthony19114** [comment]
You need to know your wallet address.....

**Comment by neurans** [comment]
Got it, I could not find them before, now I count 2 out of 3, will keep loading them. Thank you very Much!
